name: Run JuliaFormatter and create a PR

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
      - name: JuliaFormatter.format
        run: >-
          julia -e 'using JuliaFormatter: format; format(["./src/", "./test/", "./examples/", "./docs/", "./benchmark"], verbose = true, whitespace_typedefs = true, whitespace_ops_in_indices = true, remove_extra_newlines = true, always_for_in = true, margin=92)'

      # https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: Format files using JuliaFormatter
          PULL_REQUEST_TITLE: '[AUTO] Format files using JuliaFormatter'
          PULL_REQUEST_LABELS: no changelog
          PULL_REQUEST_BRANCH: create-pull-request/format
          BRANCH_SUFFIX: none
      - name: Check output environment variable
        run: echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
